# Generated by Django 4.1 on 2022-10-14 19:05

import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('mobile', models.CharField(max_length=240)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('picture', models.ImageField(default='', upload_to='shop/images')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=64)),
                ('address1', models.TextField(max_length=250)),
                ('address2', models.TextField(max_length=250)),
                ('status_changedOn', models.DateTimeField(default=datetime.datetime(2022, 10, 15, 0, 35, 50, 940036))),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_name', models.CharField(default='', max_length=64)),
                ('status_id_name', models.CharField(default='', max_length=64)),
                ('status_forecolor', models.CharField(default='', max_length=64)),
                ('status_backcolor', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Status',
            fields=[
                ('sub_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_status_name', models.CharField(default='', max_length=64)),
                ('statusForCancellation', models.BooleanField(default=False)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_field', to='base.status')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('schedule_dateTime', models.DateTimeField(default=datetime.datetime(2022, 10, 15, 0, 35, 50, 942050))),
                ('schedule_updatedateTime', models.DateTimeField(default=datetime.datetime(2022, 10, 15, 0, 35, 50, 942050))),
                ('isCompleted', models.BooleanField(default=False)),
                ('isCancelled', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(default=datetime.datetime(2022, 10, 15, 0, 35, 50, 942050))),
                ('alarm', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('durationHr', models.IntegerField()),
                ('durationMin', models.IntegerField()),
                ('lead', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2022, 10, 15, 0, 35, 50, 941195))),
                ('lead', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='substatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.sub_status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('current_role', models.CharField(max_length=64)),
                ('past_roles', models.CharField(max_length=512)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='employees', to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_statuses', models.ManyToManyField(related_name='allowed_status', to='base.sub_status')),
                ('current_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='base.sub_status')),
            ],
        ),
    ]
