# Generated by Django 4.1 on 2022-09-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_id',
        ),
    ]
