# Generated by Django 4.1 on 2022-10-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status_changedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 18, 2, 52, 792993)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 18, 2, 52, 792993)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 18, 2, 52, 793993)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 18, 2, 52, 793993)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_updatedateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 18, 2, 52, 793993)),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
