# Generated by Django 4.1 on 2022-09-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_employee_e_id_remove_team_t_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=64)),
                ('address1', models.TextField(max_length=250)),
                ('address2', models.TextField(max_length=250)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.status')),
            ],
        ),
    ]
