# Generated by Django 4.1 on 2022-09-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_lead_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
    ]
