# Generated by Django 4.1 on 2022-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_lead_status_lead_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_backcolor',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='status',
            name='status_forecolor',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
