# Generated by Django 4.1 on 2022-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_status_status_backcolor_status_status_forecolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
