# Generated by Django 4.1 on 2022-09-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_sub_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='substatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.sub_status'),
        ),
    ]
