# Generated by Django 4.1 on 2022-09-22 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_lead_status_lead_substatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2022, 9, 22, 18, 9, 22, 736848))),
            ],
        ),
    ]
