# Generated by Django 4.1 on 2022-09-22 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='lead',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.lead'),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 18, 17, 59, 768039)),
        ),
    ]
