# Generated by Django 4.1 on 2022-09-27 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_note_lead_alter_note_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 13, 41, 23, 110300)),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('schedule_dateTime', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 13, 41, 23, 111087))),
                ('added_at', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 13, 41, 23, 111087))),
                ('alarm', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('durationHr', models.IntegerField()),
                ('durationMin', models.IntegerField()),
                ('lead', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.lead')),
            ],
        ),
    ]
