# Generated by Django 4.1 on 2022-09-30 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_note_datetime_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 5, 36, 647762)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 5, 36, 647762)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 5, 36, 647762)),
        ),
        migrations.CreateModel(
            name='AllowedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_statuses', models.ManyToManyField(to='base.sub_status')),
            ],
        ),
    ]
