# Generated by Django 4.1 on 2022-09-30 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_note_datetime_alter_schedule_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedstatus',
            name='current_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='base.sub_status'),
        ),
        migrations.AlterField(
            model_name='allowedstatus',
            name='allowed_statuses',
            field=models.ManyToManyField(related_name='allowed_status', to='base.sub_status'),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 9, 48, 679917)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 9, 48, 680917)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 23, 9, 48, 680917)),
        ),
    ]
