# Generated by Django 4.1 on 2022-10-06 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_schedule_iscompleted_alter_note_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 19, 55, 27, 28740)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 19, 55, 27, 29743)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 19, 55, 27, 29743)),
        ),
    ]
