# Generated by Django 4.1 on 2022-10-06 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_schedule_iscancelled_alter_note_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_status',
            name='statusForCancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 21, 52, 36, 810540)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 21, 52, 36, 810540)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 21, 52, 36, 810540)),
        ),
    ]
