# Generated by Django 4.1 on 2022-10-13 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_schedule_status_changedon_alter_note_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='status_changedOn',
        ),
        migrations.AddField(
            model_name='lead',
            name='status_changedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 15, 33, 20, 943546)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 15, 33, 20, 943546)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 15, 33, 20, 944546)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 15, 33, 20, 944546)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_updatedateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 15, 33, 20, 944546)),
        ),
    ]
